# Generated by Django 4.0.4 on 2022-04-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='target_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
