# Generated by Django 4.0.4 on 2022-04-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_alter_posts_target_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Peoplecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='percent_now',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
